name: Sync Labels
on:
    workflow_dispatch:
    schedule:
        - cron: "0 9 * * 1"
    push:
        branches: [master, main]
jobs:
  sync-labels:
    permissions:
      issues: write
    runs-on: ubuntu-latest
    steps:
        - name: Checkout the current repository
          uses: actions/checkout@v4

