name: Sync Labels
on:
  workflow_dispatch:
  schedule:
    # 毎週月曜日の10時に実行
    - cron: "0 10 * * 1"
  push:
    branches: [main]
jobs:
  sync-labels:
    permissions:
      issues: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: micnncim/action-label-syncer@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          manifest: .github/labels.yml
